"""Tools available to the ReAct agent.

Each tool is a plain function + an OpenAI-format JSON Schema dict describing it.
The agent loop dispatches tool calls by name via TOOL_FUNCTIONS.

Error handling: tools return error strings (never raise). The LLM reads the
error in context and can adapt (retry with different params or skip the source).
"""

import os
from datetime import datetime
from pathlib import Path

import trafilatura
from ddgs import DDGS

from config import Settings

settings = Settings()


# ---------------------------------------------------------------------------
# Tool implementations
# ---------------------------------------------------------------------------


def web_search(query: str) -> str:
    """Search the web using DuckDuckGo."""
    try:
        results = DDGS().text(query, max_results=settings.max_search_results)
        if not results:
            return "No results found."
        formatted = []
        for i, r in enumerate(results, 1):
            formatted.append(
                f"{i}. Title: {r.get('title', 'N/A')}\n"
                f"   URL: {r.get('href', 'N/A')}\n"
                f"   Snippet: {r.get('body', 'N/A')}"
            )
        result = "\n\n".join(formatted)
        if len(result) > settings.max_search_content_length:
            result = result[: settings.max_search_content_length] + "\n\n[... truncated]"
        return result
    except Exception as e:
        return f"Search error: {e}"


def read_url(url: str) -> str:
    """Fetch and extract the main text content from a web page."""
    try:
        config = trafilatura.settings.use_config()
        config.set("DEFAULT", "DOWNLOAD_TIMEOUT", "10")
        downloaded = trafilatura.fetch_url(url, config=config)
        if downloaded is None:
            return f"Error: Could not fetch URL: {url}"
        text = trafilatura.extract(downloaded)
        if not text:
            return f"Error: Could not extract text from: {url}"
        if len(text) > settings.max_url_content_length:
            text = text[: settings.max_url_content_length] + "\n\n[... truncated]"
        return text
    except Exception as e:
        return f"Error reading URL: {e}"


def write_report(description: str, content: str) -> str:
    """Save a Markdown research report to the output directory."""
    try:
        os.makedirs(settings.output_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y-%m-%d_%H%M")
        slug = description.strip().replace(" ", "_").lower()
        filename = f"{timestamp}_{slug}.md"
        meta = f"> Generated by `{settings.model_name}` on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
        filepath = os.path.join(settings.output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(meta + content)
        return f"Report saved successfully to: {filepath}"
    except Exception as e:
        return f"Error saving report: {e}"


def list_reports() -> str:
    """List all previously saved research reports in the output directory."""
    try:
        output = Path(settings.output_dir)
        if not output.exists():
            return "No reports found — output directory does not exist yet."
        files = sorted(output.glob("*.md"), key=lambda f: f.stat().st_mtime, reverse=True)
        if not files:
            return "No reports found."
        return "\n".join(f"{i}. {f.name}" for i, f in enumerate(files, 1))
    except Exception as e:
        return f"Error listing reports: {e}"


def read_file(filename: str) -> str:
    """Read a previously saved report from the output directory."""
    try:
        filepath = Path(settings.output_dir) / filename
        if not filepath.exists():
            return f"Error: File not found: {filename}"
        if not filepath.resolve().is_relative_to(Path(settings.output_dir).resolve()):
            return "Error: Access denied — can only read files from the output directory."
        text = filepath.read_text(encoding="utf-8")
        if len(text) > settings.max_url_content_length:
            text = text[: settings.max_url_content_length] + "\n\n[... truncated]"
        return text
    except Exception as e:
        return f"Error reading file: {e}"


def knowledge_search(query: str) -> str:
    """Search the local knowledge base using hybrid retrieval + reranking."""
    try:
        from retriever import retrieve

        results = retrieve(query)
        if not results:
            return "No relevant documents found in the knowledge base."
        formatted = []
        for i, doc in enumerate(results, 1):
            source = Path(doc.metadata.get("source", "unknown")).name
            page = doc.metadata.get("page", "?")
            formatted.append(f"{i}. [Source: {source}, Page: {page}]\n{doc.page_content}")
        return "\n\n---\n\n".join(formatted)
    except Exception as e:
        return f"Knowledge search error: {e}"


# ---------------------------------------------------------------------------
# OpenAI tool-calling schemas
# ---------------------------------------------------------------------------

TOOL_SCHEMAS = [
    {
        "type": "function",
        "function": {
            "name": "knowledge_search",
            "description": (
                "Search the local knowledge base of ingested documents (PDFs about RAG, "
                "LLMs, LangChain, etc.). Returns relevant text chunks with source file "
                "and page references. Use this FIRST for questions about topics covered "
                "in the knowledge base, then supplement with web_search if needed."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "Search query for the knowledge base.",
                    }
                },
                "required": ["query"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "web_search",
            "description": (
                "Search the web using DuckDuckGo. Returns a list of results "
                "with title, URL, and snippet for each."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The search query string.",
                    }
                },
                "required": ["query"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "read_url",
            "description": (
                "Fetch and extract the main text content from a web page. "
                "Use this to read full articles found via web_search. "
                "The result is truncated to avoid context overflow."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "url": {
                        "type": "string",
                        "description": "The full URL of the web page to read.",
                    }
                },
                "required": ["url"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "write_report",
            "description": (
                "Save a Markdown research report to a file in the output directory. "
                "The filename is auto-generated as: YYYY-MM-DD_HHMM_<description>.md"
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "description": {
                        "type": "string",
                        "description": (
                            "Short research topic description for the filename "
                            "(e.g. 'rag_comparison'). Use lowercase with underscores, no spaces."
                        ),
                    },
                    "content": {
                        "type": "string",
                        "description": "The full Markdown content of the report.",
                    },
                },
                "required": ["description", "content"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "list_reports",
            "description": (
                "List all previously saved research reports in the output directory. "
                "Returns filenames sorted by date (newest first)."
            ),
            "parameters": {
                "type": "object",
                "properties": {},
                "required": [],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "read_file",
            "description": (
                "Read a previously saved report from the output directory. "
                "Use list_reports first to see available files."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "filename": {
                        "type": "string",
                        "description": (
                            "The filename to read (e.g. '2026-03-15_1420_rag_comparison.md')."
                        ),
                    }
                },
                "required": ["filename"],
                "additionalProperties": False,
            },
        },
    },
]

# Dispatch dict: tool name -> callable
TOOL_FUNCTIONS = {
    "knowledge_search": knowledge_search,
    "web_search": web_search,
    "read_url": read_url,
    "write_report": write_report,
    "list_reports": list_reports,
    "read_file": read_file,
}
